/**:
  ros__parameters:
    # Temporizadores:
    update_rate: 10.0
    # Restricciones de velocidad:
    horizontal_vel: 6.0
    vertical_vel: 5.0
    heading_vel: 1.5
    # Otros parámetros:
    takeoff_altitude: 5.0