# Node launch configuration
# Set to [enable, log_level]
# Enable: true launches the node, false does not
# Log levels: debug, info, warn, error, fatal

beacon_manager: [true, 'info']
drone_control: [true, 'error']
tf_manager: [true, 'error']
visualization: [true, 'error']