# Node launch configuration
# Set to [enable, log_level]
# Enable: true launches the node, false does not
# Log levels: debug, info, warn, error, fatal

drone_control: [true, 'error']
tf_manager: [true, 'error']
visualization: [true, 'error']
EIF_filter: [true, 'error']
EIF_filter_descentralized: [true, 'debug']

rosbag: true