/**:
  ros__parameters:
    # Balizas:
    beacons:
      ids: ["uwb_beacon_0", "uwb_beacon_1", "uwb_beacon_2", "uwb_beacon_3", "uwb_beacon_4", "uwb_beacon_5", "uwb_beacon_6"] 
      uwb_beacon_0:
        position: [14.9, 3.0, 2.0]
        noise_std: 1.0
        frame_id: "global"
      uwb_beacon_1:
        position: [5.5, 24.9, 7.0]
        noise_std: 1.0
        frame_id: "global"
      uwb_beacon_2:
        position: [-14.9, -2.0, 9.5]
        noise_std: 1.0
        frame_id: "global"
      uwb_beacon_3:
        position: [10.0, -24.9, 4.0]
        noise_std: 1.0
        frame_id: "global"
      uwb_beacon_4:
        position: [-13.0, -24.9, 8.0]
        noise_std: 1.0
        frame_id: "global"
      uwb_beacon_5:
        position: [-10.0, 20.0, 0.1]
        noise_std: 1.0
        frame_id: "global"
      uwb_beacon_6:
        position: [4.0, -7.0, 0.1]
        noise_std: 1.0
        frame_id: "global"