/**:
  ros__parameters:
    # Balizas:
    beacons:
      ids: ["uwb_beacon_0", "uwb_beacon_1", "uwb_beacon_2", "uwb_beacon_3"] 
      uwb_beacon_0:
        position: [5.0, 5.0, 1.2]
        noise_std: 0.004
        frame_id: "global"
      uwb_beacon_1:
        position: [-5.0, -5.0, 1.2]
        noise_std: 0.004
        frame_id: "global"
      uwb_beacon_2:
        position: [5.0, -5.0, 1.2]
        noise_std: 0.004
        frame_id: "global"
      uwb_beacon_3:
        position: [-5.0, 5.0, 1.2]
        noise_std: 0.004
        frame_id: "global"