/**:
  ros__parameters:
    # Balizas:
    beacons:
      ids: ["uwb_beacon_0", "uwb_beacon_1", "uwb_beacon_2", "uwb_beacon_3"] 
      uwb_beacon_0:
        position: [0.0, 0.0, 0.0]
        noise_std: 0.15
        frame_id: "global"
      uwb_beacon_1:
        position: [50.0, 0.0, 0.0]
        noise_std: 0.15
        frame_id: "global"
      uwb_beacon_2:
        position: [0.0, 50.0, 0.0]
        noise_std: 0.15
        frame_id: "global"
      uwb_beacon_3:
        position: [-50.0, 0.0, 0.0]
        noise_std: 0.15
        frame_id: "global"